--ALTER UMA TABELA PARA RECONFIGURAR A COLUNA Course_ID
--TORNANDO-A UMA COLUNA NÃO-NULA(NOT NULL) E PRIMARY KEY 
--(CHAVE PRIMARIA)


ALTER TABLE COURSE ALTER COLUMN Course_ID INT NOT NULL
GO

--ADICAO DE UMA RESTRICAO PARA TRANSFORMAR A COLUNA EM PK
ALTER TABLE COURSE 
ADD CONSTRAINT COURSE_PK PRIMARY KEY (Course_ID)

ALTER TABLE COURSE 
ADD CONSTRAINT FK_COURSE FOREIGN KEY (Course_ID) 

REFERENCES Course_Table_PK(Course_ID)   


--
/*
ADD UMA NOVA RESTRIÇÃO CHAMADA COURSE_PK
O TIPO DA RESTRICAO É "PRIMARY KEY" 
A COLUNA QUE VAI REPRESENTAR A PRIMARY KEY É COURSE_ID
*/







